#!/bin/bash

create_and_set() {
	original_image=$1
	battery_percentage=$2
	battery_status=$3
	image_size=`identify -format '%wx%h' $original_image`

	if [[ "$battery_status" == "Charging" || "$battery_status" == "Full" ]]; then
		color='#1793D1'
	else
		percentage_to_hsl "$battery_percentage" 0 120 # 0=red, 120=green
	fi
	convert $original_image \
		\( +clone -gravity South -crop x$battery_percentage% -fuzz 50% -fill "$color" -opaque '#8FBCBB' -background transparent -extent $image_size \) \
		-gravity Center -composite -background '#2E3440' -extent 3840x2160 $tmp_directory/background.png

	setbg $tmp_directory/background.png
	#feh --no-fehbg --bg-scale $tmp_directory/background.png
}

percentage_to_hsl() { # $percentage = $1, hue0=$2, hue1=$3
	hue=$(( ($1 * ( $3 - $2 )/100) + $2 ))
	color='hsl('$hue', 100%, 50%)'
}

find_battery_path() {
	local file
	for file in /sys/class/power_supply/*; do
	    read power_supply < "$file"/type
	    if [ "$power_supply" = "Battery" ]; then
		declare -r battery_found=1
		echo "$file"
		break
	    fi
	done

	if [ -z "$battery_found" ]; then
		echo "Couldn't find battery"
		exit 1
	fi

}

tmp_directory=/tmp/bain
file="$HOME/Pictures/system/arch.png"
mkdir -p $tmp_directory
battery_path=$(find_battery_path)
last_capacity=`< $battery_path/capacity`
last_status=`< $battery_path/status`
create_and_set $file $last_capacity $last_status

while true
do
	current_capacity=`< $battery_path/capacity`
	current_status=`< $battery_path/status`

	if [[ "$current_capacity" != "$last_capacity" ]] || [[ "$current_status" != "$last_status" ]]
	then
		create_and_set $file $current_capacity $current_status
		last_capacity=$current_capacity
		last_status=$current_status
	fi
	sleep 5
done
