#!/bin/sh

# i3blocks mail module.
# Displays number of unread mail and an loading icon if updating.
# When clicked, brings up `neomutt`.

case $BLOCK_BUTTON in
	1) "$TERMINAL" -e neomutt ;;
	2) setsid /usr/bin/mailsync >/dev/null & ;;
	3) pgrep -x dunst >/dev/null && notify-send "📬 Mail module" "\- Shows unread mail
- Shows 🔃 if syncing mail
- Left click opens neomutt
- Middle click syncs mail" ;;
esac
unreadmail=$(find ~/.local/share/mail/*/INBOX/new/ ~/.local/share/mail/*/inbox/new/ ~/.local/share/mail/*/Inbox/new/ -type f  2>/dev/null | wc -l)

if [ $unreadmail = 0 ]
then
	echo "📭 $unreadmail$(cat /tmp/imapsyncicon_$USER 2>/dev/null)"
else
	echo "📫 $unreadmail$(cat /tmp/imapsyncicon_$USER 2>/dev/null)"
fi
#echo "$(du -a ~/.local/share/mail/*/INBOX/new/* 2>/dev/null | sed -n '$=')$(cat /tmp/imapsyncicon 2>/dev/null)"
#echo $(find ~/.local/share/mail/*/INBOX/new/ ~/.local/share/mail/*/inbox/new/ ~/.local/share/mail/*/Inbox/new/ -type f  2>/dev/null | wc -l)$(cat /tmp/imapsyncicon_$USER 2>/dev/null)
