#!/bin/bash
# Presents list of all stored password entries
# Lets you choose which password to send to clipboard
selection=$(/usr/bin/gpg2 -dq $GNUPGHOME/keepass.gpg | /usr/bin/keepassxc-cli ls -q ~/Dropbox/RandomLicenceDatabaseStuff/MY\ ENTIRE\ LIFE.kdbx "General")
chosen=$(echo -e "$selection" | dmenu -i -l 20 -p "Get credentials for:")
[ "$chosen" != "" ] || exit

if [[ "$selection" == *"$chosen"* ]]
then
	username=$(gpg2 -dq $GNUPGHOME/keepass.gpg | keepassxc-cli show -a UserName -q ~/Dropbox/RandomLicenceDatabaseStuff/MY\ ENTIRE\ LIFE.kdbx "$chosen")
        notify-send "Password copied to clipboard for 10 seconds.
Username is: $username"
        gpg2 -dq $GNUPGHOME/keepass.gpg | keepassxc-cli clip -q ~/Dropbox/RandomLicenceDatabaseStuff/MY\ ENTIRE\ LIFE.kdbx "$chosen" 10
	echo "$username" | tr -d '\n' | xclip -selection clipboard
else
        notify-send "No such password found."
fi
