#!/bin/sh
icon="$HOME/Pictures/system/lock.png"
tmpbg='/tmp/screen.png'
maim -m 1 "$tmpbg"
convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
#convert "$tmpbg" -swirl 120 -gravity center "$tmpbg"
convert "$tmpbg" "$icon" -gravity center -composite -matte "$tmpbg"
i3lock -ue -i $tmpbg
